### ISSUE TITLE
How about add links to other oss lists "made-in-<country>"?

### ISSUE THREAD

**Issue by MaxGraey** [chernivtsijs/made-in-ukraine#12]
https://github.com/suguru03/made-in-canada
https://github.com/suguru03/made-in-japan
https://github.com/hueitan/made-in-taiwan
https://github.com/IonicaBizau/made-in-poland
https://github.com/IonicaBizau/made-in-brazil
https://github.com/IonicaBizau/made-in-austria 
https://github.com/IonicaBizau/made-in-romania
https://github.com/IonicaBizau/made-in-turkey
https://github.com/IonicaBizau/made-in-india
https://github.com/IonicaBizau/made-in-colombia
https://github.com/devcongress/made-in-ghana
https://github.com/ummahusla/made-in-latvia
https://github.com/made-in-bangladesh/made-in-bangladesh
https://github.com/IonicaBizau/made-in-bosnia
https://github.com/acekyd/made-in-nigeria
https://github.com/ZambianTech/made-in-zambia
https://github.com/mohebifar/made-in-iran
https://github.com/Humeira/made-in-mauritius
https://github.com/0l1v3r5/made-in-benin
https://github.com/JoloffCode/made-in-senegal

**Comment by denysdovhan** [comment]
Done!
