### ISSUE TITLE
How about add links to articles about ukrainian opensourcers

### ISSUE THREAD

**Issue by andriyor** [chernivtsijs/made-in-ukraine#13]
[GitHub-аккаунты украинских ІТшников: зачем нужны, как раскручивали и советы новичкам | DOU](https://dou.ua/lenta/articles/quiz-github/)

[«Наши» на GitHub: рейтинг | DOU](https://dou.ua/lenta/articles/github-top-10/)

**Comment by denysdovhan** [comment]
Love the idea ❤️
