### ISSUE TITLE
mourner's Mapbox projects

### ISSUE THREAD

**Issue by mourner** [chernivtsijs/made-in-ukraine#6]
I'm the author and sole maintainer for the following projects:

https://github.com/mapbox/pixelmatch
https://github.com/mapbox/earcut
https://github.com/mapbox/delaunator
https://github.com/mapbox/supercluster
https://github.com/mapbox/geojson-vt
https://github.com/mapbox/flamebearer

**Comment by denysdovhan** [comment]
done
